### ISSUE TITLE
App-Name GQL Tag Incorrect

### ISSUE THREAD

**Issue by vilenarios** [ardriveapp/ardrive-mobile-legacy#3]
One of the GraphQL Tags that is used is called "App-Name".

This is used to distinguish which application is uploading the transaction, in order to collect usage metrics.  There is a unique App-Name for each ardrive app

ArDrive-Web (used by the ardrive web app)
ArDrive-Desktop (used by the CLI and ArDrive desktop app)
ArDrive-Mobile (used by the native mobile apps)

Currently, the mobile app submits transactions and sets "App-Name" to "ArDrive-Web".  

App-Name:ArDrive-Web

You can see this here in the following transaction from the mobile app

https://viewblock.io/arweave/tx/G_HoZcOm1TqdXiqhglxycr4bry-pND3RDGbO6pAz9Mo

The Mobile app should have an "App-Name" tag that contains the string value "ArDrive-Mobile". It should look like

App-Name:ArDrive-Mobile

**Comment by isAlmogK** [comment]
Yes were using some of the web code will update thanks for seeing this

**Comment by vilenarios** [comment]
Please make sure that the Community Fees also include the App-Name:ArDrive-Mobile as well.  These are currently still labeled as ArDrive-Web

for example
https://viewblock.io/arweave/tx/PPvMYJBXL2llP-5FksNw7CiWiGgBBBUcQ4nDiOuABIc

**Comment by isAlmogK** [comment]
No problem

**Comment by vilenarios** [comment]
This issue is still happening.

Creating new issue in new repo
