### ISSUE TITLE
Delay when clicking into a Drive

### ISSUE THREAD

**Issue by vilenarios** [ardriveapp/ardrive-mobile-legacy#4]
There is a slight 1 second delay when clicking on a public/private drive.  Clicking on sub folders or clicking "back" is near instant. 

Clicking on a Drive should also instantly load the contents instead of a 1 second delay.  If the user taps twice during that delay, two "Screens" open instead.  

I have slack DMed Almog a video of this behavior since it is too big to fit here.

**Comment by isAlmogK** [comment]
@vilenarios this should already be fixed please close this out.

**Comment by vilenarios** [comment]
Issue resolved with 6/30 build (v0.4)
