### ISSUE TITLE
Display error on public file info/options modal

### ISSUE THREAD

**Issue by fedellen** [ardriveapp/ardrive-mobile-legacy#7]
On the public file info/options modal the rows are not lined up correctly and there are two `Date Created:` rows.

Edit: Also it should be "File-Id" rather than "Driver-Id" in this case

I believe @vilenarios had some other style tweaks that relate to this issue

steps:

1. Login with existing wallet
2. Open public drive
3. Open public file options/info screen

<img width="433" alt="Screen Shot 2021-06-30 at 11 42 24 AM" src="https://user-images.githubusercontent.com/60207215/124021473-349bda00-d9b1-11eb-84c8-9c5187cb4a66.png">

**Comment by isAlmogK** [comment]
@vilenarios how exactly should this be?

**Comment by vilenarios** [comment]
A few comments here:

- The first icon, the WWW with lock icon, is wrong.  This is a public file, so there should not be a lock.
- Share link still doesnt work but i think that is on the to do list.
- Remove the refresh/clock icon as it is not needed
- Driver-ID should be renamed to File-Id.  If it is a folder, it should be labeled as Folder-Id, but this should only be a COPY button
- Remove Privacy
- Size looks to be showing incorrect info
- Last Modified: the last modified time stamp in the file's metadata transaction
- Last Updated: the unix time stamp of 
- Date Created: the unix time stamp of when the file was first
- Metadata Tx ID: the transaction ID for metadata transaction of the file, but should only be a COPY button
- Data Tx ID: the transaction ID for the data transaction of the file, but should only be a COPY button

See the screen shot of the web app that shows this metadata

![image](https://user-images.githubusercontent.com/6451820/124205147-a148ce80-daae-11eb-83c3-37fe9a8cb549.png)

**Comment by vilenarios** [comment]
Also, the not to make confusing, but the file example we are using has INCORRECT UNIX TIMES written by the ArConnect app.

**Comment by vilenarios** [comment]
"Privacy" is still present in this view.  All other things have been fixed.

Creating new issue in new repo
